### ISSUE TITLE
Ikke poste kø-status om de er "0 av 0"

### ISSUE THREAD

**Issue by alfakr0ll** [benedicteb/UiO-RT-Bot#22]
TLDR: Unødvendig å poste logg fra køer om de er helt tomme.
PS: uansett greit å poste Hovedkø (Houston) slik at vi kan se stolt på oss selv og vite at botten fortsatt rapporterer.

**Comment by benedicteb** [comment]
Lagt til i https://github.com/benedicteb/Houston-Bot/commit/9316c5abb51b783331a3be187caf588b8f5181a8
